# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: financial-guardian
spec:
  selector:
    matchLabels:
      app: financial-guardian
  template:
    metadata:
      labels:
        app: financial-guardian
    spec:
      serviceAccountName: default
      terminationGracePeriodSeconds: 5
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      containers:
      - name: financial-guardian
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - all
          privileged: false
          readOnlyRootFilesystem: true
        image: financial-guardian
        imagePullPolicy: Never
        env:
        - name: VERSION
          value: "dev"
        - name: PORT
          value: "8081"
        - name: LOG_LEVEL
          value: "info"
        # Gemini AI configuration
        - name: GEMINI_API_KEY
          valueFrom:
            secretKeyRef:
              name: guardian-secrets
              key: GEMINI_API_KEY
        - name: GEMINI_MODEL
          value: "gemini-pro"
        # Bank of Anthos service endpoints
        - name: TRANSACTION_HISTORY_ADDR
          valueFrom:
            configMapKeyRef:
              name: service-api-config
              key: HISTORY_API_ADDR
        - name: LEDGER_WRITER_ADDR
          valueFrom:
            configMapKeyRef:
              name: service-api-config
              key: TRANSACTIONS_API_ADDR
        - name: BALANCE_READER_ADDR
          valueFrom:
            configMapKeyRef:
              name: service-api-config
              key: BALANCES_API_ADDR
        envFrom:
        - configMapRef:
            name: environment-config
        readinessProbe:
          httpGet:
            path: /ready
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 10
        livenessProbe:
          httpGet:
            path: /healthy
            port: 8081
          initialDelaySeconds: 60
          periodSeconds: 15
          timeoutSeconds: 30
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        volumeMounts:
        - name: tmp-dir
          mountPath: /tmp
      volumes:
      - name: tmp-dir
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: financial-guardian
spec:
  type: ClusterIP
  selector:
    app: financial-guardian
  ports:
  - name: http
    port: 8081
    targetPort: 8081
