apiVersion: skaffold/v4beta7
kind: Config
metadata:
  name: explainer-agent
build:
  artifacts:
  - image: explainer-agent
    context: .
  tagPolicy:
    gitCommit: {}
profiles:
- name: development
  activation:
  - kubeContext: minikube
  - kubeContext: docker-desktop
  deploy:
    kubectl:
      manifests:
      - k8s/deployment.yaml
  portForward:
  - resourceType: service
    resourceName: explainer-agent
    port: 8082
- name: staging
  deploy:
    kubectl:
      manifests:
      - k8s/deployment.yaml
- name: production
  build:
    artifacts:
    - image: explainer-agent
      context: .
  deploy:
    kubectl:
      manifests:
      - k8s/deployment.yaml
